version: '3'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    env_file:
      ./.env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
      - ../schema_design/scripts:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    restart: always
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
  
  postgres_to_es:
    build: ./postgres_to_es
    restart: always
    env_file:
      - ./postgres_to_es/.env
    ports:
      - 3001:3001
    depends_on:
      - redis
      - elasticsearch
      - postgres
